import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from "@/components/ui/toaster"
import { UserProvider } from '@/context/userContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}` + " bg-slate-900 text-white"}>
          <UserProvider>
            {children}
          </UserProvider>
          <Toaster />
      </body>
    </html>
  )
}
